Repository nrc-no/core, pull requests merged in 2021-12, with the labels that each got.

#250 Create creds directory on dev init
  cmd/devinit/main.go
Labels: approved, lgtm, size/S

#249 Remove unused depency in PWA
  web/pwa/package.json
  web/pwa/yarn.lock
Labels: approved, lgtm, size/S

#251 getting-started documentation updates
  docs/getting_started.md
Labels: approved, lgtm, size/M

#252 Fix missing hydraInit step in init secrets
  cmd/devinit/main.go
Labels: approved, lgtm, size/XS

#253 Fix web libraries build scripts
  scripts/build-auth.sh
  scripts/build-client.sh
  web/app/client/package.json
  web/app/client/tsconfig.build.json
  web/auth/package.json
  web/auth/tsconfig.build.json
Labels: approved, lgtm, size/M

#254 typescript dev dependency for web/app/client
  web/app/client/package.json
  web/app/client/yarn.lock
  web/auth/yarn.lock
Labels: approved, lgtm, size/M

#255 add local proxy script for mac
  Makefile
  deployments/envoy-local.yaml
  docs/getting_started.md
  scripts/proxy-local.sh
Labels: approved, lgtm, size/L

#256 fix typo with api client
  web/app/client/src/client.ts
Labels: approved, lgtm, size/XS

#257 fix designSystem build script
  scripts/build-design-system.sh
  web/designsystem/package.json
  web/designsystem/tsconfig.build.json
  web/designsystem/yarn.lock
Labels: approved, lgtm, size/S

#258 go mod tidy
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#261 COR-340-PARTIAL: Setup Test Stack
  .prow/pull-core-web-app-frontend-test.yaml
  .prow/pull-core-web-auth-test.yaml
  web/app/client/.gitignore
  web/app/client/package.json
  web/app/client/src/index.ts
  web/app/client/src/lib/client.ts
  web/app/client/src/lib/types/index.ts
  web/app/client/src/lib/utils/getFieldKind.ts
  web/app/client/src/lib/utils/index.ts
  web/app/client/src/lib/utils/responses.ts
  web/app/client/tsconfig.json
  web/app/frontend/.gitignore
  web/app/frontend/__tests__/App.test.js
  web/app/frontend/__tests__/App.test.tsx
  web/app/frontend/__tests__/__snapshots__/App.test.tsx.snap
  web/app/frontend/__tests__/utils/storage.test.ts
  web/app/frontend/jest.config.js
  web/app/frontend/jest.setup.js
  web/app/frontend/package.json
  web/app/frontend/setup.js
  web/app/frontend/src/components/form/Checkbox.tsx
  web/app/frontend/src/components/form/FormControl.tsx
  web/app/frontend/src/components/form/RadioButtons.tsx
  web/app/frontend/src/components/form/Switch.tsx
  web/app/frontend/yarn.lock
  web/auth/babel.config.js
  web/auth/package.json
  web/auth/src/components/__tests__/AuthWrapper.test.js
  web/auth/src/components/__tests__/AuthWrapper.test.tsx
  web/auth/src/types/browser.ts
  web/auth/yarn.lock
  web/designsystem/package.json
  web/designsystem/src/index.ts
  web/designsystem/tsconfig.json
  web/designsystem/yarn.lock
Labels: approved, size/XXL, lgtm

#264 Delete noop test.yaml cicd job
  .prow/test.yaml
Labels: approved, lgtm, size/S

#265 COR-369 add initial documentation for basic types
  pkg/api/types/database.go
  pkg/api/types/field.go
  pkg/api/types/field_type.go
  pkg/api/types/folder.go
  pkg/api/types/form.go
Labels: approved, lgtm, size/L

#260 COR-363 add stubs form cases & recipients
  pkg/api/types/casedef.go
  pkg/api/types/recipientdef.go
Labels: approved, lgtm, size/S

#267 COR-340 PARTIAL: Setup Linting for Frontend App
  web/app/frontend/.eslintrc.js
  web/app/frontend/.prettierrc
  web/app/frontend/package.json
  web/app/frontend/tsconfig.json
  web/app/frontend/yarn.lock
Labels: approved, lgtm, size/XL

#270 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#266 Make Recipient form extensible in the future
  pkg/api/types/casedef.go
  pkg/api/types/doc.go
  pkg/api/types/recipientdef.go
  pkg/api/types/record.go
Labels: approved, lgtm, size/L

#271 database store tests and documentation
  go.mod
  go.sum
  pkg/api/types/database.go
  pkg/server/public/handlers/database/create.go
  pkg/store/clear.go
  pkg/store/clear_test.go
  pkg/store/context.go
  pkg/store/database.go
  pkg/store/database_test.go
  pkg/store/errors.go
Labels: approved, lgtm, size/L

#259 COR-363 add basic form validation
  Makefile
  go.mod
  go.sum
  pkg/api/types/field_type.go
  pkg/api/types/field_type_test.go
  pkg/api/types/fieldkind_string.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/server/public/handlers/form/create.go
  scripts/gen.sh
Labels: approved, lgtm, size/XL

#269 COR-369 additional documentation + minor refactor/renaming + fix go tests
  .prow/push-core-go-test.yaml
  go.mod
  go.sum
  pkg/api/types/field.go
  pkg/api/types/field_type.go
  pkg/api/types/form.go
  pkg/api/types/form_interface.go
  pkg/api/types/identity_provider.go
  pkg/api/types/oauth2_client.go
  pkg/api/types/organization.go
  pkg/api/types/record.go
  pkg/api/types/user.go
  pkg/server/admin/handlers/clients/create.go
  pkg/server/admin/handlers/clients/handler.go
  pkg/server/admin/handlers/clients/mappers.go
  pkg/server/admin/handlers/clients/update.go
  pkg/sql/convert/convert.go
  pkg/sql/convert/convert_test.go
  pkg/sql/convert/create.go
  pkg/sql/schema/sql_column_constraint.go
  pkg/sql/schema/sql_data_types.go
  pkg/sql/schema/sql_data_types_test.go
  pkg/sql/schema/sql_field.go
  pkg/sql/schema/sql_field_test.go
  pkg/sql/schema/sql_schema_test.go
  pkg/sql/schema/sql_table.go
  pkg/sql/schema/sql_table_constraint.go
  pkg/sql/schema/sql_table_test.go
  pkg/store/context.go
  pkg/store/form.go
  pkg/store/organization.go
Labels: approved, size/XXL, lgtm

#275 add some tests for utility methods
  cmd/devinit/utils.go
  pkg/utils/authorization/bearertoken.go
  pkg/utils/authorization/bearertoken_test.go
  pkg/utils/files/utils.go
  pkg/utils/files/utils_test.go
  pkg/utils/pointers/pointers_test.go
  pkg/utils/sensitive/sensitive.go
  pkg/utils/sets/string.go
  pkg/utils/sets/string_test.go
  pkg/utils/slices/slice_test.go
Labels: approved, lgtm, size/L

#274 fix clear db script
  pkg/store/clear.go
  scripts/clear-db.sh
Labels: approved, lgtm, size/S

#272 Tests and documentation for the Folder store
  pkg/api/meta/utils.go
  pkg/api/types/folder.go
  pkg/api/types/scheme.go
  pkg/server/public/handlers/folder/create.go
  pkg/store/constants.go
  pkg/store/database.go
  pkg/store/database_test.go
  pkg/store/errors.go
  pkg/store/factory.go
  pkg/store/folder.go
  pkg/store/folder_test.go
  pkg/store/identity_provider.go
  pkg/store/main_test.go
Labels: approved, lgtm, size/XL

#262 COR 340 PARTIAL FormsScreen Test
  web/app/frontend/__tests__/screens/FormsScreen.test.tsx
  web/app/frontend/__tests__/screens/__snapshots__/FormsScreen.test.tsx.snap
  web/app/frontend/jest.setup.js
  web/app/frontend/package.json
  web/app/frontend/src/components/Router.tsx
  web/app/frontend/src/components/screen_containers/FormsScreenContainer.tsx
  web/app/frontend/src/components/screens/FormsScreen.tsx
  web/app/frontend/src/constants/testIds.js
  web/app/frontend/src/reducers/recordsReducers.ts
  web/app/frontend/src/types/screens.ts
  web/app/frontend/yarn.lock
Labels: approved, size/XXL, lgtm

#263 COR 340 PARTIAL FormsScreenContainer Test
  web/app/frontend/__tests__/screen_containers/FormsScreenContainer.test.js
  web/app/frontend/yarn.lock
Labels: approved, do-not-merge/contains-merge-commits, lgtm, size/XL

#277 COR-357 Add validation for records
  pkg/api/types/scheme.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/server/public/handlers/database/create.go
  pkg/server/public/handlers/form/create.go
  pkg/server/public/handlers/record/create.go
  pkg/server/public/handlers/record/update.go
  pkg/validation/errors.go
Labels: approved, lgtm, size/XL

#276 COR-356 Add validation for folders
  pkg/api/types/validation/folder.go
  pkg/api/types/validation/folder_test.go
  pkg/server/public/handlers/folder/create.go
Labels: approved, lgtm, size/L

#278 Core 381 frontend monorepo skeleton
  frontend/.gitignore
  frontend/apps/admin/package.json
  frontend/apps/native/package.json
  frontend/apps/pwa/package.json
  frontend/lerna.json
  frontend/package.json
  frontend/packages/core-api-client/package.json
  frontend/packages/core-auth/package.json
  frontend/packages/design-system/package.json
  frontend/storybook/package.json
Labels: approved, lgtm, size/L

#279 Change Record Values from map to slice
  pkg/api/types/record.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/server/public/handlers/record/create.go
  pkg/sqlmanager/build_helpers.go
  pkg/sqlmanager/build_subform_field.go
  pkg/sqlmanager/constants.go
  pkg/sqlmanager/formreader.go
  pkg/sqlmanager/formreader_test.go
  pkg/sqlmanager/formwriter.go
  pkg/sqlmanager/formwriter_test.go
  pkg/store/record.go
  pkg/testutils/options.go
  pkg/utils/pointers/pointers.go
  web/app/client/src/lib/types/index.ts
  web/app/frontend/yarn.lock
  web/pwa/src/components/RecordPicker.tsx
  web/pwa/src/features/browser/FolderBrowser.tsx
  web/pwa/src/features/browser/FormBrowser.tsx
  web/pwa/src/features/browser/RecordBrowser.tsx
  web/pwa/src/features/former/former.slice.ts
  web/pwa/src/features/recorder/FieldEditor.tsx
  web/pwa/src/features/recorder/RecordEditor.tsx
  web/pwa/src/features/recorder/recorder.slice.ts
Labels: approved, size/XXL, lgtm

#237 COR-333: add week field type
  docs/concepts.md
  go.mod
  go.sum
  pkg/api/types/field_type.go
  pkg/api/types/field_type_test.go
  pkg/api/types/fieldkind_string.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/sql/convert/convert.go
  pkg/sqlmanager/build_field.go
  pkg/sqlmanager/build_week_field.go
  pkg/sqlmanager/formreader.go
  pkg/sqlmanager/formreader_test.go
  pkg/sqlmanager/formwriter.go
  pkg/sqlmanager/formwriter_test.go
  pkg/sqlmanager/schema_test.go
  pkg/store/form.go
  pkg/testutils/options.go
  pkg/utils/dates/isoweek.go
  tools/main.go
  web/app/client/src/lib/types/index.ts
  web/auth/package.json
  web/auth/yarn.lock
  web/pwa/package.json
  web/pwa/src/features/browser/FormBrowser.tsx
  web/pwa/src/features/browser/RecordBrowser.tsx
  web/pwa/src/features/former/FieldTypePicker.tsx
  web/pwa/src/features/former/former.slice.ts
  web/pwa/src/features/recorder/FieldEditor.tsx
  web/pwa/yarn.lock
Labels: approved, lgtm, size/XL

#268 COR 340 PARTIAL AddRecordScreen Test
  web/app/client/package.json
  web/app/client/src/index.ts
  web/app/client/tsconfig.json
  web/app/frontend/__tests__/screens/AddRecordScreen.test.tsx
  web/app/frontend/__tests__/screens/__snapshots__/AddRecordScreen.test.tsx.snap
  web/app/frontend/src/components/Router.tsx
  web/app/frontend/src/components/form/FormControl.tsx
  web/app/frontend/src/components/form/TextInput.tsx
  web/app/frontend/src/components/screen_containers/AddRecordScreenContainer.tsx
  web/app/frontend/src/components/screens/AddRecordScreen.tsx
  web/app/frontend/src/constants/testIds.js
  web/app/frontend/src/utils/clients.ts
  web/app/frontend/src/utils/getNetworkState.ts
  web/app/frontend/yarn.lock
Labels: approved, size/XXL, lgtm

#280 COR 340 PARTIAL AddRecordSceenContainer Test
  web/app/client/tsconfig.build.json
  web/app/frontend/__tests__/screen_containers/AddRecordScreenContainer.test.tsx
  web/app/frontend/__tests__/screen_containers/__snapshots__/AddRecordScreenContainer.test.tsx.snap
  web/app/frontend/__tests__/screens/AddRecordScreen.test.tsx
  web/app/frontend/__tests__/screens/__snapshots__/AddRecordScreen.test.tsx.snap
  web/app/frontend/src/components/ErrorBoundary.tsx
  web/app/frontend/src/components/screen_containers/AddRecordScreenContainer.tsx
  web/app/frontend/src/components/screen_containers/ViewRecordScreenContainer.tsx
  web/app/frontend/src/components/screens/AddRecordScreen.tsx
  web/app/frontend/yarn.lock
Labels: approved, size/XXL, lgtm

#287 use new SQLManager and simplify form store implementation
  pkg/api/types/form.go
  pkg/api/types/form_interface.go
  pkg/api/types/form_interface_test.go
  pkg/api/types/record.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/server/public/handlers/form/create.go
  pkg/sql/convert/convert.go
  pkg/sql/convert/convert_test.go
  pkg/sql/convert/create.go
  pkg/sql/schema/sql_table_constraint.go
  pkg/sqlmanager/build_form.go
  pkg/sqlmanager/build_subform_field.go
  pkg/sqlmanager/formreader.go
  pkg/sqlmanager/formreader_test.go
  pkg/sqlmanager/formwriter.go
  pkg/sqlmanager/formwriter_test.go
  pkg/store/form.go
  pkg/store/form_test.go
  pkg/testutils/options.go
  pkg/validation/errors.go
  pkg/validation/validation.go
Labels: approved, size/XXL, lgtm

#283 Add API Tests to Core
  .idea/runConfigurations/test.xml
  go.mod
  go.sum
  pkg/api/types/field.go
  pkg/api/types/form.go
  pkg/api/types/record.go
  pkg/api/types/validation/record_test.go
  pkg/client/client.go
  pkg/mocks/dbfactory.go
  pkg/server/generic/server.go
  pkg/server/login/store/interface_test.go
  pkg/server/public/handlers/database/create.go
  pkg/server/public/handlers/folder/get.go
  pkg/server/public/handlers/folder/handler.go
  pkg/server/public/handlers/form/handler.go
  pkg/server/public/handlers/record/handler.go
  pkg/server/public/tests/database_test.go
  pkg/server/public/tests/doc.go
  pkg/server/public/tests/folder_test.go
  pkg/server/public/tests/form_test.go
  pkg/server/public/tests/helpers_test.go
  pkg/server/public/tests/main_test.go
  pkg/server/public/tests/record_test.go
  pkg/sqlmanager/formwriter_test.go
  pkg/sqlmanager/schema_test.go
  pkg/store/database.go
  pkg/store/factory.go
  pkg/store/form.go
  pkg/testutils/options.go
  pkg/testutils/postgres.go
  test/database_test.go
  test/folders_test.go
  test/forms_test.go
  test/main_test.go
  test/records_test.go
Labels: approved, size/XXL, lgtm

#288 COR 340 PARTIAL ViewRecordScreen test
  frontend/apps/native/__tests__/screens/ViewRecordScreen.test.tsx
  frontend/apps/native/__tests__/screens/__snapshots__/ViewRecordScreen.test.tsx.snap
  frontend/apps/native/src/components/screens/ViewRecordScreen.tsx
Labels: approved, size/XXL, lgtm

#289 Add comments to form store
  pkg/store/form.go
Labels: approved, lgtm, size/L

#284 add prow job for pwa tests and fix those tests
  frontend/apps/pwa/src/App.test.tsx
  frontend/apps/pwa/src/features/recorder/recorder.slice.spec.ts
  frontend/apps/pwa/src/reducers/__tests__/form.spec.ts
  frontend/apps/pwa/src/reducers/form.ts
Labels: approved, lgtm, size/L

#291 Configure linting for frontend
  frontend/.eslintignore
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/apps/admin/package.json
  frontend/apps/native/.eslintrc.js
  frontend/apps/native/.prettierrc
  frontend/apps/native/package.json
  frontend/apps/pwa/package.json
  frontend/package.json
  frontend/packages/core-auth/package.json
  frontend/packages/design-system/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#293 Fix react scripts eslint
  frontend/apps/admin/package.json
  frontend/apps/pwa/package.json
  frontend/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#285 COR 340 PARTIAL ViewRecordScreenContainer test
  frontend/apps/native/__tests__/screen_containers/ViewRecordScreenContainer.test.tsx
  frontend/apps/native/__tests__/screen_containers/__snapshots__/ViewRecordScreenContainer.test.tsx.snap
  frontend/apps/native/src/components/Router.tsx
Labels: approved, lgtm, size/L

#282 COR 340 PARTIAL RecordsScreen test
  frontend/apps/native/__tests__/screens/RecordsScreen.test.tsx
  frontend/apps/native/__tests__/screens/__snapshots__/RecordsScreen.test.tsx.snap
  frontend/apps/native/src/components/screen_containers/RecordsScreenContainer.tsx
  frontend/apps/native/src/components/screens/RecordsScreen.tsx
  frontend/apps/native/src/constants/routes.ts
  frontend/apps/native/src/constants/testIds.js
  frontend/apps/native/yarn.lock
  frontend/apps/pwa/yarn.lock
  frontend/packages/core-auth/yarn.lock
  frontend/storybook/yarn.lock
  frontend/yarn.lock
Labels: approved, size/XXL, lgtm

#292 add pwa to stable tests
  frontend/package.json
Labels: approved, lgtm, size/XS

#281 COR 340 PARTIAL RecordsScreenContainer test
  frontend/apps/native/__tests__/screen_containers/RecordsScreenContainer.test.tsx
  frontend/apps/native/__tests__/screen_containers/__snapshots__/RecordsScreenContainer.test.tsx.snap
  web/app/frontend/src/components/screens/RecordsScreen.tsx
Labels: approved, size/XXL, lgtm

#294 Fix storybook workspaces
  frontend/storybook/.gitignore
  frontend/storybook/metro.config.js
  frontend/storybook/package.json
  frontend/storybook/storybook/stories/Icon/Icon.stories.js
  frontend/storybook/webpack.config.js
Labels: approved, lgtm, size/M

#296 Fix expo url opening
  frontend/apps/pwa/src/App.test.tsx
  frontend/package.json
  scripts/serve-native.sh
  scripts/serve-storybook.sh
Labels: approved, lgtm, size/S

#299 Update eslint config
  frontend/.eslintrc.js
Labels: approved, lgtm, size/S

#300 Delete web/app/frontend/src/components/screens directory
  web/app/frontend/src/components/screens/RecordsScreen.tsx
Labels: approved, lgtm, size/M

#301 Lerna tweaks
  deployments/webapp.docker-compose.yaml
  frontend/apps/admin/package.json
  frontend/apps/native/src/components/Router.tsx
  frontend/apps/native/src/components/screen_containers/AddRecordScreenContainer.tsx
  frontend/apps/native/src/components/screen_containers/FormsScreenContainer.tsx
  frontend/apps/native/src/components/screen_containers/RecordsScreenContainer.tsx
  frontend/apps/native/src/components/screen_containers/ViewRecordScreenContainer.tsx
  frontend/apps/native/tsconfig.json
  frontend/apps/pwa/package.json
  frontend/package.json
  frontend/packages/core-api-client/package.json
  frontend/packages/core-api-client/tsconfig.build.json
  frontend/packages/core-api-client/tsconfig.cjs.json
  frontend/packages/core-api-client/tsconfig.esm.json
  frontend/packages/core-api-client/tsconfig.json
  frontend/storybook/tsconfig.json
  frontend/yarn.lock
  tools/local-oidc-provider/package-lock.json
  tools/local-oidc-provider/yarn.lock
Labels: approved, size/XXL, lgtm

#302 fix editorconfig to match prettier
  .editorconfig
Labels: approved, lgtm, size/XS

#303 COR-406 Core server Dockerfile
  build/package/core.Dockerfile
  build/package/core.Dockerfile.dockerignore
Labels: approved, lgtm, size/M

#306 COR-413 well-known endpoint logic fix
  frontend/packages/core-auth/src/utils/resolveDiscoveryAsync.ts
Labels: approved, lgtm, size/XS

#305 COR-411 Core pwa Dockerfile
  build/package/core-frontend.Dockerfile
  build/package/core-frontend.Dockerfile.dockerignore
  configs/core-frontend/nginx.conf.template
  configs/core-frontend/replace-env-vars.sh
Labels: approved, lgtm, size/L

#304 COR-412 Core admin Dockerfile
  build/package/authnz-frontend.Dockerfile
  build/package/authnz-frontend.Dockerfile.dockerignore
  configs/authnz-frontend/nginx.conf.template
  configs/authnz-frontend/replace-env-vars.sh
Labels: approved, lgtm, size/L

#307 COR-407 launch servers separately
  .idea/runConfigurations/serve_all.xml
  cmd/root.go
  cmd/serve.go
  cmd/serve_admin.go
  cmd/serve_all.go
  cmd/serve_auth.go
  cmd/serve_bouncer.go
  cmd/serve_login.go
  cmd/serve_public.go
Labels: approved, lgtm, size/L

#311 COR-416 remove sqljs from pwa
  frontend/apps/pwa/package.json
  frontend/apps/pwa/src/app/db.tsx
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#308 COR-414 fix authnz-bouncer path prefix
  pkg/server/auth/server.go
Labels: approved, lgtm, size/XS

#312 COR-408 do not run devinit on startup
  cmd/dev.go
  cmd/devinit/main.go
Labels: approved, lgtm, size/M

#309 COR-415 remove urls.self server option
  cmd/devinit/core.go
  pkg/server/login/handlers/login/action.go
  pkg/server/login/handlers/login/handler.go
  pkg/server/login/server.go
  pkg/server/options/options.go
Labels: approved, lgtm, size/M

#313 COR-417 documentation
  README.md
  frontend/apps/admin/README.md
  frontend/apps/pwa/README.md
  pkg/README.md
Labels: approved, lgtm, size/L

#315 COR-419 admin app env var
  cmd/devinit/core_admin_frontend.go
Labels: approved, lgtm, size/XS

#316 COR-420 remove useless cache configs
  cmd/devinit/core.go
  configs/config.yaml
Labels: approved, lgtm, size/M

#314 COR-418 build script
  Makefile
  cmd/serve_bouncer.go
  scripts/build-images.sh
Labels: approved, lgtm, size/M

#310 COR-409 fix auth token injection logic
  frontend/apps/admin/src/App.tsx
  frontend/apps/admin/src/app/client.ts
  frontend/apps/admin/src/client/client.ts
  frontend/apps/admin/src/hooks/hooks.tsx
  frontend/apps/pwa/src/App.tsx
  frontend/apps/pwa/src/app/client.ts
  frontend/apps/pwa/src/app/hooks.ts
  frontend/packages/core-api-client/src/lib/client.ts
  frontend/packages/core-auth/src/components/AuthWrapper.tsx
  frontend/packages/core-auth/src/types/types.ts
Labels: approved, lgtm, size/L

#317 COR-421 reload database connection on config change
  cmd/devinit/core.go
  cmd/serve.go
  go.mod
  go.sum
  pkg/README.md
  pkg/server/public/tests/main_test.go
  pkg/store/.gitignore
  pkg/store/factory.go
  pkg/store/factory_test.go
Labels: approved, lgtm, size/XL

#318 COR-424 fix scratch build
  build/package/core.Dockerfile
Labels: approved, lgtm, size/XS

#319 COR-424 fix docker build
  build/package/core.Dockerfile
  configs/authnz-frontend/replace-env-vars.sh
  configs/core-frontend/replace-env-vars.sh
Labels: approved, lgtm, size/XS

#320 Remove logrus logger
  cmd/clear.go
  cmd/migrate.go
  cmd/root.go
  cmd/serve.go
  go.mod
  go.sum
  pkg/server/generic/server.go
  pkg/server/login/handlers/login/action.go
  pkg/server/login/handlers/login/action_performing_auth_code_exchange.go
  pkg/utils/server.go
Labels: approved, lgtm, size/L

#328 Add a launch config to run the core api within vscode
  .gitignore
  .vscode/launch.json
Labels: approved, lgtm, size/S

#329 Rename `public` server to `formsapi` server
  cmd/devinit/core_api.go
  cmd/devinit/core_forms_api.go
  cmd/devinit/main.go
  cmd/serve_all.go
  cmd/serve_forms_api.go
  configs/config.yaml
  pkg/server/formsapi/handlers/database/create.go
  pkg/server/formsapi/handlers/database/delete.go
  pkg/server/formsapi/handlers/database/get.go
  pkg/server/formsapi/handlers/database/handler.go
  pkg/server/formsapi/handlers/database/list.go
  pkg/server/formsapi/handlers/folder/create.go
  pkg/server/formsapi/handlers/folder/delete.go
  pkg/server/formsapi/handlers/folder/get.go
  pkg/server/formsapi/handlers/folder/handler.go
  pkg/server/formsapi/handlers/folder/list.go
  pkg/server/formsapi/handlers/form/create.go
  pkg/server/formsapi/handlers/form/delete.go
  pkg/server/formsapi/handlers/form/get.go
  pkg/server/formsapi/handlers/form/handler.go
  pkg/server/formsapi/handlers/form/list.go
  pkg/server/formsapi/handlers/record/create.go
  pkg/server/formsapi/handlers/record/get.go
  pkg/server/formsapi/handlers/record/handler.go
  pkg/server/formsapi/handlers/record/list.go
  pkg/server/formsapi/handlers/record/update.go
  pkg/server/formsapi/server.go
  pkg/server/formsapi/tests/database_test.go
  pkg/server/formsapi/tests/doc.go
  pkg/server/formsapi/tests/folder_test.go
  pkg/server/formsapi/tests/form_test.go
  pkg/server/formsapi/tests/helpers_test.go
  pkg/server/formsapi/tests/main_test.go
  pkg/server/formsapi/tests/record_test.go
  pkg/server/options/options.go
Labels: approved, lgtm, size/L

#330 Rename `auth` to `authnzbouncer`
  cmd/devinit/core_authnz_bouncer.go
  cmd/devinit/main.go
  cmd/serve_all.go
  cmd/serve_authnz_bouncer.go
  configs/config.yaml
  pkg/server/authnzbouncer/authenticators/hydra.go
  pkg/server/authnzbouncer/authorizers/hydra.go
  pkg/server/authnzbouncer/handlers/handler.go
  pkg/server/authnzbouncer/server.go
  pkg/server/login/store/auth_request.go
  pkg/server/options/options.go
Labels: approved, lgtm, size/M

#331 rename `admin` to `authnzapi`
  cmd/devinit/core_admin_api.go
  cmd/devinit/main.go
  cmd/serve_all.go
  cmd/serve_authnz_api.go
  configs/config.yaml
  pkg/server/authnzapi/handlers/clients/create.go
  pkg/server/authnzapi/handlers/clients/delete.go
  pkg/server/authnzapi/handlers/clients/get.go
  pkg/server/authnzapi/handlers/clients/handler.go
  pkg/server/authnzapi/handlers/clients/list.go
  pkg/server/authnzapi/handlers/clients/mappers.go
  pkg/server/authnzapi/handlers/clients/update.go
  pkg/server/authnzapi/handlers/identityprovider/create.go
  pkg/server/authnzapi/handlers/identityprovider/get.go
  pkg/server/authnzapi/handlers/identityprovider/handler.go
  pkg/server/authnzapi/handlers/identityprovider/list.go
  pkg/server/authnzapi/handlers/identityprovider/update.go
  pkg/server/authnzapi/handlers/organization/create.go
  pkg/server/authnzapi/handlers/organization/get.go
  pkg/server/authnzapi/handlers/organization/handler.go
  pkg/server/authnzapi/handlers/organization/list.go
  pkg/server/authnzapi/server.go
  pkg/server/options/options.go
Labels: approved, lgtm, size/M

#332 update documentation to represent new names of servers
  pkg/README.md
Labels: approved, lgtm, size/L

#333 Rename admin frontend to core-authnz-frontend
  Makefile
  build/package/core-authnz-frontend.Dockerfile
  build/package/core-authnz-frontend.Dockerfile.dockerignore
  cmd/devinit/core_authnz_api.go
  cmd/devinit/core_authnz_frontend.go
  configs/core-authnz-frontend/nginx.conf.template
  configs/core-authnz-frontend/replace-env-vars.sh
  frontend/apps/core-authnz-frontend/.gitignore
  frontend/apps/core-authnz-frontend/README.md
  frontend/apps/core-authnz-frontend/package.json
  frontend/apps/core-authnz-frontend/public/favicon.ico
  frontend/apps/core-authnz-frontend/public/index.html
  frontend/apps/core-authnz-frontend/public/logo192.png
  frontend/apps/core-authnz-frontend/public/logo512.png
  frontend/apps/core-authnz-frontend/public/manifest.json
  frontend/apps/core-authnz-frontend/public/robots.txt
  frontend/apps/core-authnz-frontend/src/App.scss
  frontend/apps/core-authnz-frontend/src/App.test.tsx
  frontend/apps/core-authnz-frontend/src/App.tsx
  frontend/apps/core-authnz-frontend/src/app/client.ts
  frontend/apps/core-authnz-frontend/src/client/client.ts
  frontend/apps/core-authnz-frontend/src/components/AuthenticatedApp.tsx
  frontend/apps/core-authnz-frontend/src/components/clients/ClientEditor.tsx
  frontend/apps/core-authnz-frontend/src/components/clients/Clients.tsx
  frontend/apps/core-authnz-frontend/src/components/formcontrol/FormControl.tsx
  frontend/apps/core-authnz-frontend/src/components/navbar/NavBar.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationEditor.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationOverview.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationPortal.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationSideBar.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/Organizations.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/identityproviders/IdentityProviderEditor.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/identityproviders/IdentityProviders.tsx
  frontend/apps/core-authnz-frontend/src/components/sectiontitle/SectionTitle.tsx
  frontend/apps/core-authnz-frontend/src/hooks/hooks.tsx
  frontend/apps/core-authnz-frontend/src/index.css
  frontend/apps/core-authnz-frontend/src/index.tsx
  frontend/apps/core-authnz-frontend/src/logo.svg
  frontend/apps/core-authnz-frontend/src/react-app-env.d.ts
  frontend/apps/core-authnz-frontend/src/setupTests.ts
  frontend/apps/core-authnz-frontend/src/types/restTypes.ts
  frontend/apps/core-authnz-frontend/src/types/types.ts
  frontend/apps/core-authnz-frontend/src/types/utils.ts
  frontend/apps/core-authnz-frontend/src/utils/reportWebVitals.ts
  frontend/apps/core-authnz-frontend/src/utils/responses.ts
  frontend/apps/core-authnz-frontend/tsconfig.json
  frontend/package.json
  scripts/build-images.sh
  scripts/serve-authnz-frontend.sh
Labels: approved, lgtm, size/M

#334 Fix local tls cert paths
  configs/config.yaml
Labels: approved, lgtm, size/S

#335 Rename envoy clusters to match new naming convention
  deployments/envoy-local.yaml
  deployments/envoy.yaml
Labels: approved, lgtm, size/M

#336 Improve logging on server startup
  pkg/server/generic/server.go
Labels: approved, lgtm, size/S

#337 Fix documentation
  docs/concepts.md
Labels: approved, lgtm, size/XS

#321 parallel authentication and authorization on authnz-bouncer
  pkg/server/authnzbouncer/handlers/handler.go
Labels: approved, lgtm, size/M

#338 Change single select store implementation
  pkg/sql/schema/sql_column_constraint.go
  pkg/sqlmanager/build_single_select_field.go
  pkg/sqlmanager/schema_test.go
Labels: approved, lgtm, size/L

#339 Handle checks for null/not null single select cases
  pkg/server/formsapi/tests/record_test.go
  pkg/sqlmanager/build_single_select_field.go
  pkg/sqlmanager/schema_test.go
Labels: approved, lgtm, size/L

#340 use new app name
  cmd/devinit/core_authnz_frontend.go
Labels: approved, lgtm, size/XS

#327 DS-41: theming
  frontend/apps/native/__tests__/screen_containers/RecordsScreenContainer.test.tsx
  frontend/packages/core-auth/src/types/__tests__/browser.test.js
  frontend/packages/design-system/src/components/Button.tsx
  frontend/packages/design-system/src/components/Icon.tsx
  frontend/packages/design-system/src/components/icons/Chat.tsx
  frontend/packages/design-system/src/components/icons/Favorite.tsx
  frontend/packages/design-system/src/index.ts
  frontend/packages/design-system/src/themes/Button.ts
  frontend/packages/design-system/src/themes/index.ts
  frontend/packages/design-system/src/tokens/colors.ts
  frontend/packages/design-system/src/tokens/index.ts
  frontend/packages/design-system/src/types/types.ts
  frontend/storybook/App.tsx
  frontend/storybook/metro.config.js
  frontend/storybook/storybook/stories/Button/Button.stories.js
  frontend/storybook/storybook/stories/index.js
  frontend/storybook/webpack.config.js
Labels: approved, lgtm, size/L

#325 Cor 335 multiple selection field
  frontend/apps/pwa/package.json
  frontend/apps/pwa/src/components/RecordPicker.tsx
  frontend/apps/pwa/src/features/browser/FormBrowser.tsx
  frontend/apps/pwa/src/features/browser/RecordBrowser.tsx
  frontend/apps/pwa/src/features/former/Field.tsx
  frontend/apps/pwa/src/features/former/FieldTypePicker.tsx
  frontend/apps/pwa/src/features/former/former.slice.ts
  frontend/apps/pwa/src/features/recorder/FieldEditor.tsx
  frontend/apps/pwa/src/features/recorder/recorder.slice.ts
  frontend/packages/core-api-client/src/lib/types/index.ts
  frontend/packages/core-api-client/src/lib/utils/getFieldKind.ts
  pkg/api/types/field_type.go
  pkg/api/types/field_type_test.go
  pkg/api/types/fieldkind_string.go
  pkg/api/types/record.go
  pkg/api/types/record_test.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/server/formsapi/handlers/form/create.go
  pkg/server/formsapi/handlers/record/create.go
  pkg/server/formsapi/tests/record_test.go
  pkg/sql/schema/sql_data_types.go
  pkg/sql/schema/sql_data_types_test.go
  pkg/sqlmanager/build_field.go
  pkg/sqlmanager/build_multi_select_field.go
  pkg/sqlmanager/constants.go
  pkg/sqlmanager/formwriter.go
  pkg/sqlmanager/formwriter_test.go
  pkg/sqlmanager/handle_create_column.go
  pkg/sqlmanager/handle_create_constraint.go
  pkg/sqlmanager/handle_create_table.go
  pkg/sqlmanager/handle_insert_record.go
  pkg/sqlmanager/reader.go
  pkg/sqlmanager/reader_test.go
  pkg/sqlmanager/schema.go
  pkg/sqlmanager/writer.go
  pkg/sqlmanager/writer_test.go
  pkg/store/form.go
  pkg/store/record.go
  pkg/testutils/options.go
Labels: approved, size/XXL, lgtm

#341 DS-43: spacing
  frontend/packages/design-system/src/themes/index.ts
  frontend/packages/design-system/src/tokens/index.ts
  frontend/packages/design-system/src/tokens/spacing.ts
Labels: approved, lgtm, size/S

#342 Cor 404 dont expose axios instance
  frontend/apps/core-authnz-frontend/package.json
  frontend/apps/core-authnz-frontend/src/App.tsx
  frontend/apps/core-authnz-frontend/src/app/client.ts
  frontend/apps/core-authnz-frontend/src/client/client.ts
  frontend/apps/core-authnz-frontend/src/types/restTypes.ts
  frontend/apps/core-authnz-frontend/src/types/utils.ts
  frontend/apps/core-authnz-frontend/src/utils/responses.ts
  frontend/apps/native/App.tsx
  frontend/apps/native/src/components/AuthWrapper.tsx
  frontend/apps/native/src/utils/clients.ts
  frontend/apps/pwa/src/App.tsx
  frontend/apps/pwa/src/app/client.ts
  frontend/packages/core-api-client/src/index.ts
  frontend/packages/core-api-client/src/lib/BaseRESTClient.ts
  frontend/packages/core-api-client/src/lib/client.ts
  frontend/packages/core-api-client/src/lib/types/index.ts
  frontend/packages/core-api-client/src/lib/utils/responses.ts
  frontend/packages/core-auth/src/components/AuthWrapper.tsx
  frontend/packages/core-auth/src/types/types.ts
Labels: approved, lgtm, size/XL

#344 Serve backend command
  Makefile
  scripts/serve-backend.sh
Labels: approved, lgtm, size/M

#348 COR 445 Colombia Seeder Data
  cmd/seed_colombia.go
  pkg/seeder/colombia_dropdown_options.go
  pkg/seeder/seed.go
  pkg/seeder/seed_colombia.go
Labels: approved, do-not-merge/contains-merge-commits, size/L

#347 COR 445 Colombia Seeder Seeder Skeleton
  cmd/seed.go
  cmd/seed_colombia.go
  cmd/seed_global.go
  pkg/api/types/folder.go
  pkg/api/types/form_reference.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/seeder/colombia_dropdown_options.go
  pkg/seeder/common_field_definitions.go
  pkg/seeder/global_dropdown_options.go
  pkg/seeder/seed.go
  pkg/seeder/seed_colombia.go
  pkg/seeder/seed_global.go
  pkg/server/authnzbouncer/authorizers/hydra.go
  pkg/server/formsapi/tests/record_test.go
  pkg/sqlmanager/build_date_field.go
  pkg/sqlmanager/build_multiline_field.go
  pkg/sqlmanager/build_quantity_field.go
  pkg/utils/dates/isoweek.go
Labels: approved, lgtm, size/XL

#346 Core app setup
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/app.json
  frontend/apps/core-app/.expo-shared/assets.json
  frontend/apps/core-app/.gitignore
  frontend/apps/core-app/App.tsx
  frontend/apps/core-app/app.config.ts
  frontend/apps/core-app/app.json
  frontend/apps/core-app/assets/png/nrc.png
  frontend/apps/core-app/assets/png/search_white.png
  frontend/apps/core-app/assets/png/symbol_Hide.png
  frontend/apps/core-app/assets/png/symbol_close.png
  frontend/apps/core-app/assets/png/symbol_filter.png
  frontend/apps/core-app/assets/png/symbol_individuals.png
  frontend/apps/core-app/assets/png/symbol_more.png
  frontend/apps/core-app/assets/svg/nrc.svg
  frontend/apps/core-app/assets/svg/search_white.svg
  frontend/apps/core-app/assets/svg/symbol_Hide.svg
  frontend/apps/core-app/assets/svg/symbol_close.svg
  frontend/apps/core-app/assets/svg/symbol_filter.svg
  frontend/apps/core-app/assets/svg/symbol_individuals.svg
  frontend/apps/core-app/assets/svg/symbol_more.svg
  frontend/apps/core-app/babel.config.js
  frontend/apps/core-app/metro.config.js
  frontend/apps/core-app/package.json
  frontend/apps/core-app/src/clients/formsClient.ts
  frontend/apps/core-app/src/components/AuthWrapper/AuthWrapper.test.tsx
  frontend/apps/core-app/src/components/AuthWrapper/AuthWrapper.tsx
  frontend/apps/core-app/src/components/AuthWrapper/index.ts
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.test.ts
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
  frontend/apps/core-app/src/navigators/index.ts
  frontend/apps/core-app/src/navigators/root.tsx
  frontend/apps/core-app/src/screens/LoginScreen/LoginScreen.component.test.tsx
  frontend/apps/core-app/src/screens/LoginScreen/LoginScreen.component.tsx
  frontend/apps/core-app/src/screens/LoginScreen/LoginScreen.styles.ts
  frontend/apps/core-app/src/screens/LoginScreen/__snapshots__/LoginScreen.component.test.tsx.snap
  frontend/apps/core-app/src/screens/LoginScreen/index.ts
  frontend/apps/core-app/src/store/hooks.ts
  frontend/apps/core-app/src/store/store.ts
  frontend/apps/core-app/src/testUtils/render.tsx
  frontend/apps/core-app/src/types/.gitkeep
  frontend/apps/core-app/tsconfig.json
  frontend/apps/core-app/webpack.config.js
  frontend/apps/native/src/components/form/FormControl.tsx
  frontend/apps/native/src/components/screens/RecordsScreen.tsx
  frontend/package.json
  frontend/packages/core-api-client/src/lib/utils/getFieldKind.ts
  frontend/yarn.lock
  scripts/serve-backend.sh
Labels: approved, size/XXL, lgtm

#238 COR-347: implement infering form name for subforms from their parent
  frontend/apps/pwa/src/components/AuthenticatedApp.tsx
  frontend/apps/pwa/src/features/former/Former.tsx
  frontend/apps/pwa/src/features/former/FormerContainer.tsx
  scripts/up.sh
Labels: approved, lgtm, size/L

#349 COR-445 Columbia Seeder
  cmd/seed.go
  cmd/seed_colombia.go
  cmd/seed_global.go
  pkg/api/types/folder.go
  pkg/api/types/form_reference.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/seeder/colombia_dropdown_options.go
  pkg/seeder/common_field_definitions.go
  pkg/seeder/global_dropdown_options.go
  pkg/seeder/seed.go
  pkg/seeder/seed_colombia.go
  pkg/seeder/seed_global.go
  pkg/server/authnzbouncer/authorizers/hydra.go
  pkg/server/formsapi/tests/record_test.go
  pkg/sqlmanager/build_date_field.go
  pkg/sqlmanager/build_multiline_field.go
  pkg/sqlmanager/build_quantity_field.go
  pkg/utils/dates/isoweek.go
Labels: approved, lgtm, size/XL

#352 COR-446-Fix_PWA_forms_display
  frontend/apps/pwa/src/features/browser/FolderBrowser.tsx
  frontend/apps/pwa/src/features/browser/browser.slice.ts
  frontend/apps/pwa/src/reducers/__tests__/form.spec.ts
  frontend/apps/pwa/src/reducers/form.ts
Labels: approved, lgtm, size/L
