Repository nrc-no/core, pull requests merged in 2022-04, with the labels that each got.

#397 BACKBONE-0: Add CI to build docker image and auto-deploy in staging
  .prow/push-core-build.yaml
Labels: approved, lgtm, size/S

#398 BACBKONE-0: Fix dockerfile to work with kaniko build
  build/package/core-authnz-frontend.Dockerfile
  build/package/core-frontend.Dockerfile
Labels: lgtm, size/S

#396 Cor 486 registration page validation
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/CheckboxFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/DateFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/MonthFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/MultiSelectFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/MultilineTextFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/QuantityFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/ReferenceFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/SingleSelectFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/SubFormFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/TextFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/WeekFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/CheckboxFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/MultiSelectFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/MultilineTextFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/QuantityFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/SubFormFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/TextFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.component.tsx
  frontend/packages/core-api-client/src/client/Recipient.ts
  frontend/packages/core-api-client/src/client/__tests__/Recipient.test.ts
  frontend/packages/core-api-client/src/index.ts
  frontend/packages/core-api-client/src/validation/Recipient.ts
  frontend/packages/core-api-client/src/validation/Record.ts
  frontend/packages/core-api-client/src/validation/index.ts
Labels: approved, lgtm, size/L

#400 Large navigation header
  frontend/apps/core-app/App.tsx
  frontend/apps/core-app/app.json
  frontend/apps/core-app/assets/png/nrc_logo.png
  frontend/apps/core-app/assets/png/nrc_logo_with_text.png
  frontend/apps/core-app/assets/svg/nrc.svg
  frontend/apps/core-app/src/components/Link/Link.component.tsx
  frontend/apps/core-app/src/components/Link/index.ts
  frontend/apps/core-app/src/components/NavHeader/LargeNavHeader.component.tsx
  frontend/apps/core-app/src/components/NavHeader/__tests__/LargeNavHeader.component.test.tsx
  frontend/apps/core-app/src/components/NavHeader/__tests__/__snapshots__/LargeNavHeader.component.test.tsx.snap
  frontend/apps/core-app/src/components/NavHeader/index.ts
  frontend/apps/core-app/src/components/NavHeader/logout.ts
  frontend/apps/core-app/src/components/Recipient/RecipientEditor/__tests__/__snapshots__/RecipientEditor.components.test.tsx.snap
  frontend/apps/core-app/src/components/Recipient/RecipientViewer/__tests__/__snapshots__/RecipientViewer.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecipientListTable/RecipientListTableFilter/__tests__/__snapshots__/RecipientListTableFilter.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecipientListTable/RecipientListTableFilter/__tests__/__snapshots__/RecipientListTableFilter.container.test.tsx.snap
  frontend/apps/core-app/src/components/RecipientListTable/__tests__/__snapshots__/RecordTableRow.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/CheckboxFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/MultiSelectFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/MultilineTextFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/QuantityFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/ReferenceFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/SingleSelectFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/SubFormFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/TextFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordView/__tests__/__snapshots__/FieldValue.component.test.tsx.snap
  frontend/apps/core-app/src/constants/routes.ts
  frontend/apps/core-app/src/navigation/linking.config.ts
  frontend/apps/core-app/src/navigation/recipients.tsx
  frontend/apps/core-app/src/navigation/root.tsx
  frontend/apps/core-app/src/screens/LoginScreen/__tests__/__snapshots__/LoginScreen.component.test.tsx.snap
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.component.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/RecipientRegistrationScreen.container.test.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/__snapshots__/RecipientRegistrationScreen.component.test.tsx.snap
  frontend/apps/native/assets/svg/nrc.svg
  frontend/packages/design-system/src/themes/Link.ts
  frontend/packages/design-system/src/themes/index.ts
  frontend/packages/design-system/src/tokens/colors.ts
Labels: approved, lgtm, size/XL
