Repository nrc-no/core, pull requests merged in 2022-02, with the labels that each got.

#368 add repo display names to tests
  frontend/apps/core-app/package.json
  frontend/apps/core-app/src/screens/LoginScreen/__snapshots__/LoginScreen.component.test.tsx.snap
  frontend/apps/core-authnz-frontend/package.json
  frontend/apps/pwa/package.json
  frontend/packages/core-api-client/package.json
  frontend/packages/core-auth/package.json
  frontend/packages/design-system/package.json
  frontend/storybook/package.json
  frontend/yarn.lock
Labels: approved, size/XXL, lgtm

#370 Cor 463 rename field type boolean to field type check box
  frontend/apps/pwa/src/components/FieldEditor/FieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/CheckboxFieldEditor.tsx
  frontend/apps/pwa/src/features/former/Field.tsx
  frontend/apps/pwa/src/features/former/FieldTypePicker.tsx
  frontend/apps/pwa/src/reducers/former.ts
  frontend/packages/core-api-client/src/lib/types/index.ts
  frontend/packages/core-api-client/src/lib/utils/getFieldKind.ts
  frontend/yarn.lock
  pkg/api/types/field_type.go
  pkg/api/types/field_type_test.go
  pkg/api/types/fieldkind_string.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/seeder/common_field_definitions.go
  pkg/sql/schema/sql_data_types_test.go
  pkg/sqlmanager/build_boolean_field.go
  pkg/sqlmanager/build_field.go
  pkg/sqlmanager/reader.go
  pkg/sqlmanager/reader_test.go
  pkg/sqlmanager/writer.go
  pkg/sqlmanager/writer_test.go
  pkg/store/form.go
  pkg/store/form_test.go
  pkg/testutils/options.go
Labels: approved, lgtm, size/XL

#371 Cor 467 forms client refactoring
  frontend/apps/native/src/components/screen_containers/AddRecordScreenContainer.tsx
  frontend/apps/native/src/components/screen_containers/FormsScreenContainer.tsx
  frontend/apps/native/src/components/screen_containers/RecordsScreenContainer.tsx
  frontend/apps/native/src/components/screen_containers/ViewRecordScreenContainer.tsx
  frontend/apps/pwa/src/features/databases/DatabaseEditor.tsx
  frontend/apps/pwa/src/features/folders/FolderEditor.tsx
  frontend/apps/pwa/src/reducers/Former/former.reducers.ts
  frontend/apps/pwa/src/reducers/Recorder/recorder.reducers.ts
  frontend/apps/pwa/src/reducers/database.ts
  frontend/apps/pwa/src/reducers/folder.ts
  frontend/apps/pwa/src/reducers/form.ts
  frontend/apps/pwa/src/reducers/records.ts
  frontend/packages/core-api-client/src/index.ts
  frontend/packages/core-api-client/src/lib/client.ts
  frontend/packages/core-api-client/src/lib/client/BaseRESTClient.ts
  frontend/packages/core-api-client/src/lib/client/Client.ts
  frontend/packages/core-api-client/src/lib/client/Database.ts
  frontend/packages/core-api-client/src/lib/client/Folder.ts
  frontend/packages/core-api-client/src/lib/client/Form.ts
  frontend/packages/core-api-client/src/lib/client/Record.ts
  frontend/packages/core-api-client/src/lib/client/index.ts
  frontend/packages/core-api-client/src/lib/types/client/Client.ts
  frontend/packages/core-api-client/src/lib/types/client/Database.ts
  frontend/packages/core-api-client/src/lib/types/client/Folder.ts
  frontend/packages/core-api-client/src/lib/types/client/Form.ts
  frontend/packages/core-api-client/src/lib/types/client/Record.ts
  frontend/packages/core-api-client/src/lib/types/client/index.ts
  frontend/packages/core-api-client/src/lib/types/client/utils.ts
  frontend/packages/core-api-client/src/lib/types/index.ts
  frontend/packages/core-api-client/src/lib/types/model/Database.ts
  frontend/packages/core-api-client/src/lib/types/model/Field.ts
  frontend/packages/core-api-client/src/lib/types/model/Folder.ts
  frontend/packages/core-api-client/src/lib/types/model/Form.ts
  frontend/packages/core-api-client/src/lib/types/model/Record.ts
  frontend/packages/core-api-client/src/lib/types/model/index.ts
  frontend/packages/core-api-client/src/lib/types/model/model.ts
  frontend/packages/core-api-client/src/lib/utils/index.ts
  frontend/packages/core-api-client/src/lib/utils/responses.ts
  frontend/packages/core-api-client/tsconfig.json
Labels: approved, size/XXL, lgtm

#373 COR-471: add tests for custom validation
  frontend/apps/pwa/src/features/former/FormerContainer.tsx
  frontend/apps/pwa/src/features/former/FormerField.tsx
  frontend/apps/pwa/src/features/former/__tests__/validation.spec.ts
  frontend/apps/pwa/src/features/former/validation.ts
Labels: approved, lgtm, size/L

#379 Base client rest methods
  frontend/.eslintrc.js
  frontend/package.json
  frontend/packages/core-api-client/src/lib/client/BaseRESTClient.ts
  frontend/packages/core-api-client/src/lib/types/client/utils.ts
  frontend/packages/core-api-client/src/lib/utils/responses.ts
Labels: approved, lgtm, size/L

#378 COR-466: recipient form validation
  frontend/apps/pwa/src/features/former/Former.tsx
  frontend/apps/pwa/src/features/former/__tests__/validation.spec.ts
  frontend/apps/pwa/src/features/former/validation.ts
Labels: approved, lgtm, size/L

#374 COR-468: input theming
  frontend/apps/core-app/App.tsx
  frontend/apps/core-app/src/screens/LoginScreen/__snapshots__/LoginScreen.component.test.tsx.snap
  frontend/packages/design-system/src/assets/iconMap.ts
  frontend/packages/design-system/src/assets/icons/Error.tsx
  frontend/packages/design-system/src/assets/icons/Success.tsx
  frontend/packages/design-system/src/assets/icons/index.ts
  frontend/packages/design-system/src/themes/Button.ts
  frontend/packages/design-system/src/themes/FormControlErrorMessage.ts
  frontend/packages/design-system/src/themes/FormControlHelperText.ts
  frontend/packages/design-system/src/themes/FormControlLabel.ts
  frontend/packages/design-system/src/themes/Icon.ts
  frontend/packages/design-system/src/themes/Input.ts
  frontend/packages/design-system/src/themes/Text.ts
  frontend/packages/design-system/src/themes/index.ts
  frontend/packages/design-system/src/tokens/index.ts
  frontend/packages/design-system/src/tokens/radii.ts
  frontend/packages/design-system/src/tokens/spacing.ts
  frontend/packages/design-system/src/tokens/typography.ts
  frontend/storybook/App.tsx
  frontend/storybook/storybook/stories/Button/Button.stories.js
  frontend/storybook/storybook/stories/Input/Input.stories.js
  frontend/storybook/storybook/stories/index.js
Labels: approved, lgtm, size/L

#375 COR-480: add missing text styles
  frontend/apps/core-app/src/screens/LoginScreen/__snapshots__/LoginScreen.component.test.tsx.snap
  frontend/packages/design-system/src/themes/Button.ts
  frontend/packages/design-system/src/themes/FormControlErrorMessage.ts
  frontend/packages/design-system/src/themes/FormControlHelperText.ts
  frontend/packages/design-system/src/themes/FormControlLabel.ts
  frontend/packages/design-system/src/themes/Input.ts
  frontend/packages/design-system/src/themes/Text.ts
  frontend/packages/design-system/src/themes/index.ts
  frontend/packages/design-system/src/tokens/typography.ts
  frontend/storybook/storybook/stories/Input/Input.stories.js
  frontend/storybook/storybook/stories/Text/Text.stories.js
Labels: approved, lgtm, size/L
