Repository nrc-no/core, pull requests merged in 2022-01, with the labels that each got.

#354 COR-437: redirect to form after saving it
  frontend/apps/pwa/src/features/former/FormerContainer.tsx
Labels: approved, lgtm, size/M

#353 COR-425-Fix_token_renewal
  frontend/apps/core-app/App.tsx
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.test.ts
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
  frontend/apps/core-authnz-frontend/src/App.tsx
  frontend/apps/native/App.tsx
  frontend/apps/pwa/src/App.tsx
  frontend/apps/pwa/src/app/hooks.ts
  frontend/packages/core-api-client/src/lib/BaseRESTClient.ts
  frontend/packages/core-auth/src/components/AuthWrapper.tsx
  frontend/packages/core-auth/src/hooks/useDiscovery.ts
  frontend/packages/core-auth/src/types/request.ts
  frontend/packages/core-auth/src/types/response.ts
  frontend/packages/core-auth/src/types/types.ts
  scripts/serve-backend.sh
Labels: approved, lgtm, size/L

#355 COR-436: redirect to record after submitting, refactoring
  frontend/apps/core-authnz-frontend/src/hooks/hooks.tsx
  frontend/apps/pwa/src/app/store.ts
  frontend/apps/pwa/src/components/AuthenticatedApp.tsx
  frontend/apps/pwa/src/components/FieldEditor/FieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/DateFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/FieldDescription.tsx
  frontend/apps/pwa/src/components/formFields/FieldLabel.tsx
  frontend/apps/pwa/src/components/formFields/MonthFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/MultiSelectFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/MultilineTextFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/QuantityFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/ReferenceFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/SelectOptionsList.tsx
  frontend/apps/pwa/src/components/formFields/SingleSelectFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/SubFormFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/SubRecord.tsx
  frontend/apps/pwa/src/components/formFields/SubRecordList.tsx
  frontend/apps/pwa/src/components/formFields/TextFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/WeekFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/index.ts
  frontend/apps/pwa/src/components/formFields/types.ts
  frontend/apps/pwa/src/features/browser/FolderBrowser.tsx
  frontend/apps/pwa/src/features/browser/RecordBrowser.tsx
  frontend/apps/pwa/src/features/browser/RecordField.tsx
  frontend/apps/pwa/src/features/browser/RecordFieldList.tsx
  frontend/apps/pwa/src/features/former/Former.tsx
  frontend/apps/pwa/src/features/former/FormerContainer.tsx
  frontend/apps/pwa/src/features/recorder/FieldEditor.tsx
  frontend/apps/pwa/src/features/recorder/RecordEditor.component.tsx
  frontend/apps/pwa/src/features/recorder/RecordEditor.container.tsx
  frontend/apps/pwa/src/features/recorder/RecordEditor.tsx
  frontend/apps/pwa/src/features/recorder/index.ts
  frontend/apps/pwa/src/reducers/__tests__/recorder.spec.ts
  frontend/apps/pwa/src/reducers/browser.ts
  frontend/apps/pwa/src/reducers/former.ts
  frontend/apps/pwa/src/reducers/recorder.ts
  frontend/apps/pwa/src/reducers/records.ts
Labels: approved, size/XXL, lgtm

#357 COR-388: access token in session store
  frontend/packages/core-auth/src/components/AuthWrapper.tsx
  frontend/packages/core-auth/src/types/response.ts
  frontend/packages/core-auth/src/utils/__tests__/getJSONFromSessionStorage.test.js
  frontend/packages/core-auth/src/utils/getJSONFromSessionStorage.ts
Labels: approved, lgtm, size/L

#358 Eas build
  cmd/devinit/core_native_app.go
  frontend/apps/core-app/.gitignore
  frontend/apps/core-app/app.json
  frontend/apps/core-app/eas.json
  frontend/apps/core-app/index.js
  frontend/apps/core-app/package.json
  frontend/apps/core-app/src/screens/LoginScreen/__snapshots__/LoginScreen.component.test.tsx.snap
  frontend/apps/core-authnz-frontend/package.json
  frontend/apps/native/package.json
  frontend/apps/pwa/package.json
  frontend/lerna.json
  frontend/package.json
  frontend/storybook/app.json
  frontend/storybook/package.json
  frontend/yarn.lock
  scripts/eas-build.sh
Labels: approved, size/XXL, lgtm

#359 COR-456: Fix multiselect field rendering in record editor
  frontend/apps/pwa/src/components/formFields/MultiSelectFieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/SelectOptionsList.tsx
Labels: approved, lgtm, size/S

#361 COR-457: Respect white space when rendering multiline text
  frontend/apps/pwa/src/features/browser/FormBrowser.tsx
  frontend/apps/pwa/src/features/browser/RecordField.tsx
Labels: approved, lgtm, size/L

#363 Cor 442 add yes no field type
  frontend/apps/pwa/src/components/FieldEditor/FieldEditor.tsx
  frontend/apps/pwa/src/components/formFields/BooleanFieldEditor.tsx
  frontend/apps/pwa/src/features/former/Field.tsx
  frontend/apps/pwa/src/features/former/FieldTypePicker.tsx
  frontend/apps/pwa/src/reducers/former.ts
  frontend/packages/core-api-client/src/lib/types/index.ts
  frontend/packages/core-api-client/src/lib/utils/getFieldKind.ts
  frontend/yarn.lock
  pkg/api/types/field_type.go
  pkg/api/types/field_type_test.go
  pkg/api/types/fieldkind_string.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/api/types/validation/record.go
  pkg/api/types/validation/record_test.go
  pkg/seeder/common_field_definitions.go
  pkg/seeder/global_dropdown_options.go
  pkg/sqlmanager/build_boolean_field.go
  pkg/sqlmanager/build_field.go
  pkg/sqlmanager/reader.go
  pkg/sqlmanager/reader_test.go
  pkg/sqlmanager/writer.go
  pkg/sqlmanager/writer_test.go
  pkg/store/form.go
  pkg/store/form_test.go
  pkg/testutils/options.go
Labels: approved, size/XXL, lgtm

#365 COR-499 add form type
  frontend/packages/core-api-client/src/lib/types/index.ts
  pkg/api/types/defaults/form.go
  pkg/api/types/form.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/form_test.go
  pkg/server/formsapi/handlers/form/create.go
  pkg/server/formsapi/tests/form_test.go
  pkg/store/form.go
  pkg/store/form_test.go
Labels: approved, lgtm, size/L

#366 COR-450 add validation for recipient forms
  pkg/api/types/scheme.go
  pkg/api/types/validation/form.go
  pkg/api/types/validation/recipient.go
  pkg/api/types/validation/recipient_test.go
  pkg/server/formsapi/handlers/form/create.go
  pkg/server/formsapi/handlers/form/create_test.go
Labels: approved, lgtm, size/L

#367 COR-451 Recipient seed
  Makefile
  cmd/seed.go
  pkg/seeder/common_field_definitions.go
  pkg/seeder/seed_colombia.go
  pkg/seeder/seed_global.go
  scripts/seed.sh
Labels: approved, lgtm, size/M
