Repository nrc-no/core, pull requests merged in 2022-05, with the labels that each got.

#401 More auth fixes
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
Labels: approved, lgtm, size/S

#403 Return empty list, instead of null, when there are no forms
  pkg/store/form.go
Labels: approved, lgtm, size/XS

#402 Recipient form leaf nodes
  frontend/apps/core-app/App.tsx
  frontend/apps/core-app/src/components/NavHeader/LargeNavHeader.component.tsx
  frontend/apps/core-app/src/config.ts
  frontend/apps/core-app/src/constants/routes.ts
  frontend/apps/core-app/src/contexts/RecipientForms.tsx
  frontend/apps/core-app/src/contexts/__tests__/RecipientForms.test.tsx
  frontend/apps/core-app/src/navigation/recipients.tsx
  frontend/apps/core-app/src/navigation/root.tsx
  frontend/apps/core-app/src/navigation/types.ts
  frontend/apps/core-app/src/screens/RecipientListScreen/RecipientListScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientProfileScreen/RecipientProfileScreen.component.tsx
  frontend/apps/core-app/src/screens/RecipientProfileScreen/RecipientProfileScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientProfileScreen/__tests__/__snapshots__/RecipientProfileScreen.component.test.tsx.snap
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.component.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/RecipientRegistrationScreen.container.test.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/__snapshots__/RecipientRegistrationScreen.component.test.tsx.snap
  frontend/apps/core-app/src/testUtils/mockData/Form.ts
  frontend/apps/core-app/src/testUtils/navigation.ts
  frontend/packages/core-api-client/src/client/Recipient.ts
  frontend/packages/core-api-client/src/client/__tests__/Recipient.test.ts
  frontend/packages/core-api-client/src/types/client/Recipient.ts
  frontend/packages/core-api-client/src/utils/__tests__/tree.test.ts
  frontend/packages/core-api-client/src/utils/tree.ts
Labels: approved, lgtm, size/XL

#408 COR-474: use sso scopes
  pkg/server/login/handlers/login/utils.go
Labels: approved, lgtm, size/XS
