Repository nrc-no/core, pull requests merged in 2022-03, with the labels that each got.

#387 Add stubs for recipient registration child components
  frontend/apps/core-app/package.json
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/CheckboxFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/DateFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/FieldInput.container.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/MonthFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/MultiSelectFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/MultilineTextFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/ReferenceFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/SingleSelectFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/SubFormFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/TextFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/WeekFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/index.ts
  frontend/apps/core-app/src/components/RecordEditor/RecordEditor.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/RecordEditor.container.tsx
  frontend/apps/core-app/src/components/RecordEditor/index.ts
  frontend/apps/core-app/src/components/RecordView/__tests__/__snapshots__/FieldValue.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordView/__tests__/__snapshots__/SubformFieldValue.component.test.tsx.snap
  frontend/apps/core-app/src/config.ts
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.component.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/RecipientRegistrationScreen.component.test.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/__snapshots__/RecipientRegistrationScreen.component.test.tsx.snap
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/buildDefaultRecord.test.ts
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/buildDefaultRecord.ts
  frontend/packages/design-system/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/XL

#388 unify versions of native base
  frontend/apps/core-app/package.json
  frontend/apps/native/package.json
  frontend/apps/pwa/package.json
  frontend/package.json
  frontend/packages/design-system/package.json
  frontend/storybook/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/L

#389 Expo fixes
  cmd/devinit/core_native_app.go
  frontend/apps/core-app/.gitignore
  frontend/apps/core-app/app.json
  frontend/apps/core-app/babel.config.js
  frontend/apps/core-app/eas.json
  frontend/apps/core-app/index.js
  frontend/apps/core-app/package.json
  frontend/yarn.lock
Labels: approved, lgtm, size/M

#391 Cor 486 registration page submit
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.test.ts
  frontend/apps/core-app/src/components/Recipient/RecipientEditor/RecipientEditor.component.tsx
  frontend/apps/core-app/src/components/Recipient/RecipientEditor/__tests__/RecipientEditor.components.test.tsx
  frontend/apps/core-app/src/components/Recipient/RecipientEditor/__tests__/__snapshots__/RecipientEditor.components.test.tsx.snap
  frontend/apps/core-app/src/components/Recipient/RecipientEditor/index.ts
  frontend/apps/core-app/src/components/Recipient/RecipientViewer/RecipientViewer.component.tsx
  frontend/apps/core-app/src/components/Recipient/RecipientViewer/__tests__/RecipientViewer.component.test.tsx
  frontend/apps/core-app/src/components/Recipient/RecipientViewer/__tests__/__snapshots__/RecipientViewer.component.test.tsx.snap
  frontend/apps/core-app/src/components/Recipient/RecipientViewer/index.ts
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/SubFormFieldInput.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/FieldInput/__tests__/__snapshots__/SubFormFieldInput.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordEditor/RecordEditor.component.tsx
  frontend/apps/core-app/src/components/RecordEditor/RecordEditor.container.tsx
  frontend/apps/core-app/src/components/RecordEditor/__tests__/__snapshots__/RecordEditor.component.test.tsx.snap
  frontend/apps/core-app/src/components/RecordView/RecordView.component.tsx
  frontend/apps/core-app/src/components/RecordView/RecordView.container.tsx
  frontend/apps/core-app/src/components/RecordView/RecordView.types.ts
  frontend/apps/core-app/src/components/RecordView/__tests__/normaliseFieldValues.test.ts
  frontend/apps/core-app/src/components/RecordView/normaliseFieldValues.ts
  frontend/apps/core-app/src/hooks/__tests__/useAPICall.test.ts
  frontend/apps/core-app/src/hooks/useAPICall.ts
  frontend/apps/core-app/src/screens/RecipientProfileScreen/RecipientProfileScreen.component.tsx
  frontend/apps/core-app/src/screens/RecipientProfileScreen/RecipientProfileScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientProfileScreen/__tests__/RecipientProfileScreen.component.test.tsx
  frontend/apps/core-app/src/screens/RecipientProfileScreen/__tests__/__snapshots__/RecipientProfileScreen.component.test.tsx.snap
  frontend/apps/core-app/src/screens/RecipientProfileScreen/__tests__/prettifyData.test.ts
  frontend/apps/core-app/src/screens/RecipientProfileScreen/prettifyData.ts
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.component.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/RecipientRegistrationScreen.container.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/RecipientRegistrationScreen.component.test.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/RecipientRegistrationScreen.container.test.tsx
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/__snapshots__/RecipientRegistrationScreen.component.test.tsx.snap
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/__tests__/buildDefaultFormValues.test.ts
  frontend/apps/core-app/src/screens/RecipientRegistrationScreen/buildDefaultFormValues.ts
  frontend/apps/core-app/src/utils/ReactHookFormTransformer.ts
  frontend/apps/core-app/src/utils/__test__/ReactHookFormTransformer.test.ts
  frontend/apps/core-app/src/utils/__test__/buildDefaultRecord.test.ts
  frontend/apps/core-app/src/utils/buildDefaultRecord.ts
Labels: approved, size/XXL, lgtm

#393 Auth fixes
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.test.ts
  frontend/apps/core-app/src/components/AuthWrapper/useTokenResponse.ts
Labels: approved, lgtm, size/M

#384 migrate to react-router v6
  frontend/apps/core-authnz-frontend/package.json
  frontend/apps/core-authnz-frontend/src/App.tsx
  frontend/apps/core-authnz-frontend/src/components/AuthenticatedApp.tsx
  frontend/apps/core-authnz-frontend/src/components/Router.tsx
  frontend/apps/core-authnz-frontend/src/components/clients/ClientEditor.tsx
  frontend/apps/core-authnz-frontend/src/components/clients/Clients.tsx
  frontend/apps/core-authnz-frontend/src/components/navbar/NavBar.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationOverview.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationPortal.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/OrganizationSideBar.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/Organizations.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/identityproviders/IdentityProviderEditor.tsx
  frontend/apps/core-authnz-frontend/src/components/organizations/identityproviders/IdentityProviders.tsx
  frontend/apps/core-authnz-frontend/src/hooks/hooks.tsx
  frontend/apps/pwa/package.json
  frontend/apps/pwa/src/App.tsx
  frontend/apps/pwa/src/Router.tsx
  frontend/apps/pwa/src/components/AuthenticatedApp.tsx
  frontend/apps/pwa/src/features/browser/Browser/AddFolderButton.tsx
  frontend/apps/pwa/src/features/browser/Browser/AddFormButton.tsx
  frontend/apps/pwa/src/features/browser/Browser/Browser.component.tsx
  frontend/apps/pwa/src/features/browser/Browser/Browser.container.tsx
  frontend/apps/pwa/src/features/browser/Browser/DatabaseBrowser.container.tsx
  frontend/apps/pwa/src/features/browser/Browser/EmptyState.tsx
  frontend/apps/pwa/src/features/browser/Browser/FolderBrowser.container.tsx
  frontend/apps/pwa/src/features/browser/Browser/index.ts
  frontend/apps/pwa/src/features/browser/Browser/types.ts
  frontend/apps/pwa/src/features/browser/FolderBrowser.tsx
  frontend/apps/pwa/src/features/browser/FolderRow.tsx
  frontend/apps/pwa/src/features/browser/FormBrowser.tsx
  frontend/apps/pwa/src/features/databases/DatabaseEditor.tsx
  frontend/apps/pwa/src/features/folders/FolderEditor.tsx
  frontend/apps/pwa/src/features/former/FormerContainer.tsx
  frontend/apps/pwa/src/features/navbar/navbar.tsx
  frontend/apps/pwa/src/features/recorder/RecordEditor.container.tsx
  frontend/storybook/package.json
  frontend/yarn.lock
Labels: approved, size/XXL, lgtm
